### ISSUE TITLE
No Content error 

### ISSUE THREAD

**Issue by ElChurcho** [coder-alpha/FMoviesPlus.bundle#1]
Tested on Iphone and Samsung smart tv, PS4
Redirector enabled. 

 After selecting an item during the load of the sources, open load google 1 it brings back no content.

**Comment by coder-alpha** [comment]
Are you seeing the Google playback server when you navigate to the video ?

They seem to have made some changes yesterday so I'm not seeing any links show up on my end.

**Comment by ElChurcho** [comment]
No. Cannot see any playback servers. No content available.

Thank You

Scott Felton

**Comment by coder-alpha** [comment]
New version is now up. Please update and let me know if you are having issues with Google-1 server. If yes, then please read this post ---> https://forums.plex.tv/discussion/comment/1418516/#Comment_1418516

**Comment by ElChurcho** [comment]
Looks to be resolved.
