### ISSUE TITLE
What is the function D in function 'get_token' in fmovies.py ?

### ISSUE THREAD

**Issue by divyanshshukla13** [coder-alpha/FMoviesPlus.bundle#11]
[Link](https://github.com/coder-alpha/FMoviesPlus.bundle/blob/7e983d2a539fe44861886a8713d5b0760d0c9de7/Contents/Code/fmovies.py#L362) to the code snippet.
Also can you please explain how this thing works ?
Thanks.

**Comment by coder-alpha** [comment]
D in Plex is base64 decode

get_token function is broken atm, they seem to have changed the code...

it mimics the js code on their site to decode the _ _underscore_ value to be included in the request url. The other parameters are used as keys
eg:
```
../menu-bar?ts=1494316800&_=687
../update-views?ts=1494316800&_=1086&id=qxw1v&I=1
../info?ts=1494316800&_=1107&id=p8w2rx&update=0
```

**Comment by coder-alpha** [comment]
Btw, whats your interest ? Are u writing a plugin too ?

**Comment by divyanshshukla13** [comment]
Not exactly a plugin, but I was trying to write a CLI scraper for fmovies. 
@coder-alpha  Do you know of any working code of fmovies video link scraper btw ?

**Comment by coder-alpha** [comment]
I have updated my code in ver. 0.20 and should be working now.

**Comment by divyanshshukla13** [comment]
Thanks a lot. 👍

**Comment by coder-alpha** [comment]
Good luck !

**Comment by techreligion** [comment]
../menu-bar?ts=1494316800&_=687
../update-views?ts=1494316800&_=1086&id=qxw1v&I=1
../info?ts=1494316800&_=1107&id=p8w2rx&update=0
