### ISSUE TITLE
Algorithm to obtain 'r1' while setting cookies

### ISSUE THREAD

**Issue by divyanshshukla13** [coder-alpha/FMoviesPlus.bundle#13]
[Link](https://github.com/coder-alpha/FMoviesPlus.bundle/blob/master/Contents/Code/fmovies.py#L194)

Can you explain what is 'r1' here ?

I'm able to get 'session' and '__cfuid' cookies but not 'reqkey'.  Can you please elaborate a bit on
how to obtain that ?

**Comment by coder-alpha** [comment]
the reqkey cookie is set by the site from this url (https://fmovies.to/token) using JS... the JS is obfuscated using [jsf#ck](http://jsfuck.com)... 
You will need to decode the obfuscated code using a JS engine/routine like below
https://jsfiddle.net/codyA/ss3wweoc/embedded/result/

or 

if you're looking for a pure python routine look at [jsfdecoder](https://github.com/coder-alpha/FMoviesPlus.bundle/blob/master/Contents/Libraries/Shared/resources/lib/libraries/jsfdecoder.py). It currently can handle only simpler obfuscated code.

**Comment by cpa311** [comment]
this is the only channel I watch but every time I load it I get "video unavailable error: token" is there something on my end that I need to do to get it to work?

**Comment by mikedrawback** [comment]
@cpa311 see [this thread](https://forums.plex.tv/discussion/255348/rel-fmoviesplus-channel) for information about reqkey token issues.

**Comment by cpa311** [comment]
Thank you so much mikedrawback that thread helped me to get it working.
