### ISSUE TITLE
error:list index out of range

### ISSUE THREAD

**Issue by cpa311** [coder-alpha/FMoviesPlus.bundle#14]
When I try to load a show on fmovies I get this error "error: list index out of range"  How do I go about fixing this.

Thank you for any help you can give. fmovies is the only thing I watch.. I'm lost without it.

**Comment by coder-alpha** [comment]
https://forums.plex.tv/discussion/comment/1476298/#Comment_1476298

Will post an update in a few hours.

**Comment by coder-alpha** [comment]
v.0.37 is up. please test and let me know.

**Comment by cpa311** [comment]
It's working. Thank you so much.
