### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by NE03N** [coder-alpha/FMoviesPlus.bundle#16]
i get the message "No Items Available"

OSX Sierra

Great bundle in any case...

**Comment by coder-alpha** [comment]
Tested on OSX Sierra.. seems to work for me. Are you on v. 0.39 and have enabled SSL Alternate option under channel settings/prefs ?
Try a more generic search terms like 'gold', if still getting "No Items Available" try Reset Cookies under the Options menu and try again.
 If issue persists channel log files would be helpful.

**Comment by NE03N** [comment]
everything's working fine now thank you!
