### ISSUE TITLE
auto upate error

### ISSUE THREAD

**Issue by eetjtl** [coder-alpha/FMoviesPlus.bundle#19]
I saw the error on auto update again.(no error last update) It still updates just get that error.

So here is the log section if it might help, (looks like it "times out" then does the get a second time)

Nov 18, 2017 10:13:25.935 [3552] DEBUG - [com.plexapp.plugins.fmoviesplus] Sending command: GET /:/prefixes
Nov 18, 2017 10:13:25.940 [3600] ERROR - Error issuing curl_easy_perform(handle): 56
Nov 18, 2017 10:13:25.941 [3600] WARN - HTTP error requesting GET http://127.0.0.1:49367/video/fmoviesplus/update?url=https%3A%2F%2Fgithub.com%2Fcoder-alpha%2FFMoviesPlus.bundle%2Farchive%2Fv0.50.zip&ver=0.50 (0, No error) (Recv failure: Connection was reset)
Nov 18, 2017 10:13:25.941 [3600] DEBUG - [com.plexapp.plugins.fmoviesplus] HTTP reply status -56, with 0 bytes of content.
Nov 18, 2017 10:13:25.975 [2584] DEBUG - Completed: [10.0.0.103:35684] 500 GET /video/fmoviesplus/update?url=https%3A%2F%2Fgithub.com%2Fcoder-alpha%2FFMoviesPlus.bundle%2Farchive%2Fv0.50.zip&ver=0.50 (15 live) GZIP 3225ms 170 bytes (pipelined: 1).

**Comment by coder-alpha** [comment]
@eetjtl 
Not exactly sure but I have the [update process run in a thread](https://github.com/coder-alpha/FMoviesPlus.bundle/blob/master/Contents/Code/updater.py#L89-L90) once it completes the primary one from the main thread. For some reason it was needed on Ubuntu (can't recollect now what was the reason behind it). 
I'm guessing the fact that it installs fine, the Channels is restarting when this 2nd update process is running and shuts it down with Connection was reset message. If that is indeed the case then its expected in a way but I'll keep an eye on it. Thanks for the note.

**Comment by coder-alpha** [comment]
Keeping an eye on this but closing for now, please re-open if the issue resurfaces.
