### ISSUE TITLE
All links disappeared/can't play item

### ISSUE THREAD

**Issue by Shadyelements17** [coder-alpha/FMoviesPlus.bundle#2]
This app has always worked fine for me, I was watching it a couple hours ago when out of nowhere every link either stopped working or disappeared. The titles are still there, but when I click it will bring up the page where the links usually are but with no links or it will skip that part and go straight to the box popping up and saying cannot play item. I've tried this on movies and tv shoes it's doing it to everything, please help. I love this app it's the only app that I use.

**Comment by coder-alpha** [comment]
@Shadyelements17 try out the new version.
