### ISSUE TITLE
Not able to play any video

### ISSUE THREAD

**Issue by rdudeja1133** [coder-alpha/FMoviesPlus.bundle#21]
I download new bundle  but still getting error messages. Also seeing message - "Pairing required"..what is that what do I need to pair with. Please fix the issue

Regards
RD

**Comment by coder-alpha** [comment]
@rdudeja1133 
Please read the first post in the forum thread, the installation section in specific to see how to avoid the pairing requirement or the Help video under the channel menu regarding 'How to pair with OpenLoad'.
"Pairing required" message is not an issue.

Please make a separate issue for any error messages with the Channel log file as mentioned in the first post.
