### ISSUE TITLE
FMoviesPlus Channel - This channel is not responding

### ISSUE THREAD

**Issue by RHungerschafer** [coder-alpha/FMoviesPlus.bundle#22]
After upgrade to FMoviesPlus v0.57 the FMoviesPlus channel disappeared.  After several re-installs it reappeared. but now All movies, shows and even the Options tab: “This channel is not responding.” Prior to interface loading Options are accessible.

FMoviesPlus 0.57
Plex Web Version 3.27.1
Plex Server Version 1.10.1.4602

Please advise.

Bob

[com.plexapp.plugins.fmoviesplus.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594713/com.plexapp.plugins.fmoviesplus.log)
[com.plexapp.system.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594714/com.plexapp.system.log)
[DebugLog.txt](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594715/DebugLog.txt)
[FMoviesPlusIssues.docx](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594716/FMoviesPlusIssues.docx)
[InstallerLogs_Plex Media Server_20171224105310.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594717/InstallerLogs_Plex.Media.Server_20171224105310.log)
[Plex Media Server.1.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594718/Plex.Media.Server.1.log)
[Plex Media Server.2.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1594719/Plex.Media.Server.2.log)

**Comment by RHungerschafer** [comment]
Tried multiple solutions:
1) Turned off firewall
2) downloading and installing new Services and Framework bundles. Did not work.
3) Deleting Services and Framework bundles. Did not work.
Now the error message on categories like sizzlers states to try enabling SSL in preferences, but it is already enabled, so tried disabling and re-enabling, but the error still recommends enabling SSL.

**Comment by coder-alpha** [comment]
Based on the channel log file (com.plexapp.plugins.fmoviesplus.log) it shows multiple errors which don't make any sense. Almost as if multiple files are missing.

I would suggest doing a clean install, stopping Plex, delete the FMoviesPlus bundle, download the latest copy and install that and start Plex.

**Comment by RHungerschafer** [comment]
Uninstalled, restart, new install, used Web Tools to install new bundle.  Same errors.  Logs attached.

[FMoviesPlus Errors 20180101.docx](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1596336/FMoviesPlus.Errors.20180101.docx)
[Plex Media Server.zip](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1596337/Plex.Media.Server.zip)

Thanks,

Bob

**Comment by coder-alpha** [comment]
Installation is fine now.

Set the following in settings:
Base URL: https://bmovies.pro
Use SSL Web-Proxy: False/Disabled

Do a Clear Cache and Reset Cookie and then try a video.

**Comment by RHungerschafer** [comment]
That seems to have done it.  Don't know how it got to that state, but glad it is working now.  

Thanks for everything!
