### ISSUE TITLE
Can I enter an openload link ??

### ISSUE THREAD

**Issue by joaquin-becerra** [coder-alpha/FMoviesPlus.bundle#23]
Yes, is not an issue, is a feature

I would like to be able to enter my own openload links, many times the movies of the catalogs are not in the language I want, but I have links that I want to see on my android tv

Would it be possible?

Great job!

**Comment by coder-alpha** [comment]
yes, thats possible. let me get some fixes done, then will work on this.

**Comment by coder-alpha** [comment]
Implemented in /dev branch for now https://github.com/coder-alpha/FMoviesPlus.bundle/commits/dev

Navigate to Options > Interface Options > External Hosts > OpenLoad > Tools > Enter OpenLoad Video ID
