### ISSUE TITLE
ssl isnt working

### ISSUE THREAD

**Issue by djwayne1985** [coder-alpha/FMoviesPlus.bundle#24]
as it states the ssl isnt working even if i tick the alternate ssl is selected i still get this error.

Cookie not set ! Please try Reset Cookies under the Options menu.

i have the latest version of plex media server running on synology dsm 6.1 please if you can help me with this matter it would be a big help thanks in advance

**Comment by coder-alpha** [comment]
The "Cookie not set ! Please try Reset Cookies under the Options menu." error is due to some site changes and not related to ssl. I should have a fix out tomorrow, give that a try and let me know how that fares.

**Comment by coder-alpha** [comment]
plz try v.0.63 and confirm if issue persists
