### ISSUE TITLE
Downloads Reset

### ISSUE THREAD

**Issue by RHungerschafer** [coder-alpha/FMoviesPlus.bundle#25]
Often is pairing expires during download they fail.  When attempting to download the same item there is a message that it is already in the queue, therefore it will not add again, but it also does not restart.  For some reason I am unable to enter to see completed, failed or all.  It would be nice if there was an option to clear the download queue so subsequent downloads can be started fresh.

Bob

**Comment by coder-alpha** [comment]
once you pair again your download should be able to resume downloading. there are also options to remove a download.

**Comment by coder-alpha** [comment]
plz try with v. 0.63 and confirm if issue still persists. should be fixed now.
