### ISSUE TITLE
Video Unavailable. Error: token

### ISSUE THREAD

**Issue by RHungerschafer** [coder-alpha/FMoviesPlus.bundle#26]
For every video keep getting "Video Unavailable. Error: token" but the word "token" is not in the error log.

[com.plexapp.plugins.fmoviesplus.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1790988/com.plexapp.plugins.fmoviesplus.log)

Bob

**Comment by AllviewTV** [comment]
I'm having the same issue. Forked the hook.io address as well but still no joy. Having to use externals for now

**Comment by coder-alpha** [comment]
Will be fixed in the update tomorrow.

**Comment by coder-alpha** [comment]
Fixed
