### ISSUE TITLE
Parse Error when accessing Device Options on atv2

### ISSUE THREAD

**Issue by ananchev** [coder-alpha/FMoviesPlus.bundle#28]
I am using FMoviesPlus and accessing PMS via PlexConnect on a jailbroken atv2 as client. 
Have two identical aTVs, the Device Options on one can be accessed without problem, on the the  other I am getting Parse Error.
![parse_error](https://user-images.githubusercontent.com/34111833/42114076-0aada634-7bee-11e8-8488-1b3633a173a5.JPG)

**Comment by coder-alpha** [comment]
It seems like its unable to display the Vibrant emoji icon and errors on it. Did you have that option enabled by any chance ?
You could try and do a factory reset of the plugin and see if it resolves the issue.

![image](https://user-images.githubusercontent.com/10291660/42116517-246f1bbc-7c15-11e8-9e7d-e2f79f2cfba1.png)

**Comment by ananchev** [comment]
I have tried resetting few times, but it did not help. Interestingly on the other atv2, the client options menu is visualised without issues - same PMS. 
Looked throughly in the plugin logs - nothing caught my eye. Can send if you think might help.
Where are the client options stored? Can I set editing server conf files? I am after the option to use phantomJS.

**Comment by ananchev** [comment]
BTW, tried updating to v0.71 and attempted to use the default setting to use PhantonJS, but with this version getting  "local variable 'isTargetPlay' referenced before assignment" when trying to play content.

**Comment by coder-alpha** [comment]
In the latest v0.71 you can set the PhantomJS option under Settings to "Yes-Universally",

I'll look into the issue, do make sure you have a clean  0.71 installation.

**Comment by ananchev** [comment]
hi coder-alpha - following your advice above, I installed completely clean 0.71, the latest PhantomJS, and set Use PhantomJS to Yes-Universally. Now when browsing Movies& TV-Series and any of the sub-menus under I get "This plugin is not responding." Find the fmoviesplus logfile attached - seems PhantomJS is working....
[com.plexapp.plugins.fmoviesplus.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/2151622/com.plexapp.plugins.fmoviesplus.log)

**Comment by coder-alpha** [comment]
Seems like a cache issue now since it seems to be working fine for one section. Try a PMS restart and do a Clear Cache (under Options) and if using Plex-Web do a cache clearance of your browser too and then lemme know how things are.

**Comment by ananchev** [comment]
Clear Cache did the job - now the plugin works as expected. Thanks!
The client options are still not accessible on one of my clients, but actually are not needed too with the option to force via Settings.

**Comment by coder-alpha** [comment]
Added a fix for this in v.0.72
