### ISSUE TITLE
when attempting to play video capcha is needed

### ISSUE THREAD

**Issue by JohnEngland65** [coder-alpha/FMoviesPlus.bundle#29]
phantom is checked in options and copied to phantom directory. It appears that the phantom has issues. Version 70 work withput capcha.
Thx Coder for your hard work and teaching

**Comment by coder-alpha** [comment]
With version 0.70 the PhantomJS option is a dropdown field and should be set as following and then you dont need to worry about setting it under Device Options.

![image](https://user-images.githubusercontent.com/10291660/42116209-efa1a18a-7c13-11e8-8314-546572a8548a.png)

**Comment by JohnEngland65** [comment]
That was it thanks coder....Thanks for what you do!
