### ISSUE TITLE
Update Errors

### ISSUE THREAD

**Issue by Shadyelements17** [coder-alpha/FMoviesPlus.bundle#3]
Hi, I updated yesterday and this app worked perfect again, woke up this morning it wasnt working. I saw that you released a new update a couple hours ago so I updated it again and now it's say page was not received when I click on anything. Thanks for the reply in advance.

**Comment by Shadyelements17** [comment]
I found the fix, I switched to dev instead of the master and now it's working.

**Comment by coder-alpha** [comment]
Thanks for the note.
