### ISSUE TITLE
Error: Token

### ISSUE THREAD

**Issue by AllviewTV** [coder-alpha/FMoviesPlus.bundle#30]
Everything was working fine no issues at all then yesterday I got 'Error: Token' so went in to options and reset cookies and got the same issue. Ive tried resetting the cookies at least 20 times and also tried factory resetting the plugin and nothing is working for me. Do you have any ideas?

**Comment by coder-alpha** [comment]
Which version are u using ? It should probably be asking to use PhantomJS which you need for uninterrupted usage since the token has been changing very frequently by the website.

**Comment by AllviewTV** [comment]
I have PhantomJS set to Universal. Is there anything else I need to do?

**Comment by AllviewTV** [comment]
I'm using bmovies.pro and using the movies section. It's started working again now. I just left it for a couple of hours and it started working oerfect again

**Comment by coder-alpha** [comment]
Hmm.. can you let me know the exact section when it happens again. If you have PhantomJS set to 'Yes-Universally' then you should not face this issue unless you are trying one of the Anime sections.
