### ISSUE TITLE
Not finding sources

### ISSUE THREAD

**Issue by sirthought** [coder-alpha/FMoviesPlus.bundle#32]
All TV programs and most movies find no sources for stream or download. The status page just shows the sources progress as at 10% (before reinstall it was saying 0%). This just started happening in the past two or three days while using ver 0.71. To test, I uninstalled and reinstalled the plugin via Webtools. I have PhantomJS turned on and have paired to Openload. I have tried multiple base site URLs with no change.

**Comment by coder-alpha** [comment]
If you are looking for links under the External Sources then do make sure under your Interface Options the Providers are enabled and working. The progress indicator will increase once you refresh after a few sec/min.
If you are using PhantomJS then set it to 'Yes-Universally' and then you don't need to worry about pairing anymore.
If you are using External Listing then you dont need to worry about the Base Site url since that is independent of the website.

Finally, if you can provide a few examples it would help to replicate. I have tried a few and they all seem to work as expected.

**Comment by sirthought** [comment]
Thanks for the follow up. I do appreciate it. This is still a mystery. Just updated your latest today. I checked my setup options. All of the providers and enabled. I have attempted to refresh multiple times, but the screen indicated the same results (no content) and the same percent of progress each time. (Screen shots attached.) PhantomJS is set to Yes-Universally now, although I've had this working for about a year or so without having messed with that at all. 
<img width="1600" alt="screen shot 2018-07-13 at 2 16 59 am" src="https://user-images.githubusercontent.com/41130180/42675771-803e0394-8643-11e8-8aec-bf4ea240b0c9.png">
<img width="1597" alt="screen shot 2018-07-13 at 2 15 11 am" src="https://user-images.githubusercontent.com/41130180/42675774-805ac542-8643-11e8-8aa7-7dc727b4b1bc.png">
<img width="724" alt="screen shot 2018-07-13 at 2 13 53 am" src="https://user-images.githubusercontent.com/41130180/42675775-80768aac-8643-11e8-88b6-552a6e4d9b69.png">
<img width="723" alt="screen shot 2018-07-13 at 2 13 22 am" src="https://user-images.githubusercontent.com/41130180/42675776-8091c16e-8643-11e8-8cd1-fe77c9744056.png">

**Comment by coder-alpha** [comment]
It looks to me something has not updated properly. For a clean install I suggest.. shutdown Plex, delete the FMoviesPlus bundle, download a new copy, install the new bundle. Sometimes some processes can be running and wont allow proper update when copied over.

If you have PhantomJS path within the bundle then you will need to copy it again. I suggest defining the path to some other location so it doesnt get deleted.

I did a test and I can see the results show up..
As you can see the progress is now visible, the checkmarked ones are done, the ones with ↯ show current ones and ↭ are still waiting to be processed.

![image](https://user-images.githubusercontent.com/10291660/42689960-86d8afb0-8670-11e8-95b8-247fe2bf082f.png)

![image](https://user-images.githubusercontent.com/10291660/42689985-9dfcf840-8670-11e8-9b27-eefa53805d57.png)

**Comment by coder-alpha** [comment]
Hoping the clean install fixed the issue, otherwise please re-open this issue. Thanks.

**Comment by sirthought** [comment]
Tried the clean install after you had advised it, but sadly no change. I will try your recent update. Thanks.

**Comment by coder-alpha** [comment]
If you are still facing issues after a clean install of the new version then please also attach the fmoviesplus log files after you have enabled the debug option from the channels settings/prefs menu and tried a few items.

**Comment by sirthought** [comment]
I'm having the issue again where this app is not finding sources for downloads. After your last update it was working great until sometime last week. I've also noticed in the process of searching for sources I'm getting an Avast popup telling me it's blocking what I think is a cryptocurrency miner. Attaching some files to help you see what I'm experiencing. Thank you.
[com.plexapp.plugins.fmoviesplus.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/2351615/com.plexapp.plugins.fmoviesplus.log)
<img width="1600" alt="screen shot 2018-09-05 at 2 51 27 am" src="https://user-images.githubusercontent.com/41130180/45076545-adbb3b80-b0b8-11e8-91aa-38c86101c580.png">
<img width="1600" alt="screen shot 2018-09-05 at 2 49 06 am" src="https://user-images.githubusercontent.com/41130180/45076546-adbb3b80-b0b8-11e8-833c-b82f9d91cd4d.png">
<img width="1600" alt="screen shot 2018-09-05 at 2 48 44 am" src="https://user-images.githubusercontent.com/41130180/45076547-ae53d200-b0b8-11e8-8873-0f911ed1ab3f.png">
<img width="972" alt="screen shot 2018-09-05 at 2 48 02 am" src="https://user-images.githubusercontent.com/41130180/45076549-ae53d200-b0b8-11e8-8e6c-c8c9d29253e7.png">

**Comment by sirthought** [comment]
[com.plexapp.plugins.fmoviesplus.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/2351618/com.plexapp.plugins.fmoviesplus.log)

**Comment by coder-alpha** [comment]
Just from the screencap you have posted you have only FMovies and Primewire enabled. You might want to [enable a few more Providers](https://github.com/coder-alpha/FMoviesPlus.bundle/issues/43#issuecomment-417196436) to get best results.

Regarding the block by Avast, some websites use Javascript coinmining scripts which come into play if you were browsing. However, when using the Plex plugin those scripts are not executed. The plugins scrapes the video link only. If you have a good understanding you can add Plex to your whitelist or leave it as is - it affects only a few hosters.

**Comment by coder-alpha** [comment]
Assuming this is resolved now.
