### ISSUE TITLE
Please wait a few seconds for the Interface to Load & Initialize plugins

### ISSUE THREAD

**Issue by GentoSan** [coder-alpha/FMoviesPlus.bundle#34]
Hi
I have this issue when I use my Plex, either on my server or the client. When I choose any tab (category) this message pops up and nothing happens.

"Please wait a few seconds for the Interface to Load & Initialize plugins" 

What's the problem over here?

Edit 1: I'm using macOS.

**Comment by coder-alpha** [comment]
Is this a new install or an upgrade and how much time have you waited ?
The Initialization can take from a few seconds to a couple of minutes depending upon a few factors. You can enable the option under the Settings to have a Quick Initialization.
If this is an upgrade try to do a clean install by stopping Plex, deleting the old bundle and then downloading a new copy to install.

**Comment by coder-alpha** [comment]
Hoping the clean install did the trick, closing for now.
