### ISSUE TITLE
Error: local variable 'IsTargetPlay' referenced before assignment

### ISSUE THREAD

**Issue by AllviewTV** [coder-alpha/FMoviesPlus.bundle#37]
Everytime I click on streamango or openload I keep getting this error. The plugin was working perfect a few days ago but seems to be doing this now

**Comment by coder-alpha** [comment]
Not exactly sure where that is being produced. Can you provide a log ?

**Comment by scottywh** [comment]
I had this problem recently after upgrading versions through my roku app.  Reinstalled manually and restarted PMS and voila, no more problems.

**Comment by coder-alpha** [comment]
Yeah, most of the issues do get resolved after a clean manual install. Hoping this got resolved, closing for now.
