### ISSUE TITLE
The plugin is not responding

### ISSUE THREAD

**Issue by MrShrumpert** [coder-alpha/FMoviesPlus.bundle#38]
so i've had a few problems updating to the new version, but the other threads have helped clear up all but one issue.  i followed the advice for loading times; that worked great.  the one issue i can't seem to get rid of is the plugin not responding no matter which base site url I use.  fmovies.se worked for a short period, but i ran into the issue of not finding sources.  i followed the steps in the other thread and had sources pop up, but then i would get this "the plugin is not responding" issue when trying almost anything within the program (i.e. try and search, open bookmarks, open whats hot, sometimes just trying to open the app).  the plugin disappeared for a while and wouldn't even show in plex until i reinstalled phantomjs (and updated it's new location under settings).  every time i switch base sites, i restart plex and give it 10-20 minutes to load up and still get this message.  i've tried everything i know how to do; any advice?

i'm using windows 10 and a roku 3, west coast NA, comcast internet with 180down/15up.

EDIT: i let it set over night to see if i wasn't giving it enough time to load.  i then ran into the cookie problem, so i installed JRE and restarted and it seems to be working just fine now.

**Comment by coder-alpha** [comment]
The site had been running slow and might have contributed to your issue. Can you download the new version and let me know if problem still persists. Please re-open this issue if that is the case.
