### ISSUE TITLE
Fmovies no openload or streamango directory.

### ISSUE THREAD

**Issue by JohnEngland65** [coder-alpha/FMoviesPlus.bundle#39]
when a movie is chose it only shows external sources and no openload etc...

**Comment by zablon123** [comment]
to expand - it looks like all openload/streamango/rapidvideo internal links no longer show up. Movies have some external links, but TV shows have none at all.

**Comment by coder-alpha** [comment]
Yeah they have encrypted that section of the webpage. Will try and get a fix out for this soon.

**Comment by scottywh** [comment]
Thanks coder-alpha!

**Comment by coder-alpha** [comment]
@JohnEngland65 @zablon123 @scottywh 
New version with fix is now up https://github.com/coder-alpha/FMoviesPlus.bundle/releases/tag/v0.73
Could you guys test it and let me know.

Cheers !

**Comment by Oldpapa** [comment]
Working

**Comment by zablon123** [comment]
Working great!
