### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by nedsolanki** [coder-alpha/FMoviesPlus.bundle#40]
HI Coder-Alpha,

Now that the other forum is not letting us discuss the issue, I am just wondering if the Issue I am getting is mine alone or others find it.

my Fmovies loads fine, but when I go to look for a film or tv series, I git switch the SSL switch in the channel options.  I have done this repeatedly, but it keeps saying the same thing.  I haven't uploaded the logs at this stage as I am not sure if it's needed.  My PMS is on ubuntu latest version and also the plex server is also the latest none-plex pass on as well.  Any suggestions?

**Comment by nedsolanki** [comment]
Sorry, Also running 0.73 which was loaded last night.  I have also rebooted my server as well everytime a new update is loaded on.

**Comment by coder-alpha** [comment]
Enable the Alternate SSL option under settings. Then navigate to Options menu and run Clear Cache and Reset Cookies. If you are using Plex-web clear your browser cache and then try to use the plugin and see if that resolves your issue.

**Comment by nedsolanki** [comment]
Yeap done that previously as well.  This is the error I get _HTTP Code 0 for https://bmovies.pro/home. Enable SSL option in Channel Prefs._, 

and here is the channel setting screen

![image](https://user-images.githubusercontent.com/42269597/43955623-efd33c0e-9c98-11e8-8d03-4af760c7c296.png)

I cleared the browser on my TV as well as my laptop and also tried on a new built VM as well

I have switch off the SSL for both web-proxy and ALT SSL/TLS as well. and rebooted the server, but keep getting the error message or get the clear the cache and try again message.

any other suggestions.  BTW thanks for the quick response as well as a great Plugin.

**Comment by nedsolanki** [comment]
Also want to add.  I am based in the UK on Virgin Cable.  I have also tried all the websites as well, clearing the cache and cookies for each one.

**Comment by Oldpapa** [comment]
Looking at it.. You have too many options checked off and not enuf of the other.
Uncheck all the use and disables
Raise the source searching to like 10
Raise the download threads to maybe 6
Save it and exit fmovies.
Start the channel again clear cache and the other then check

**Comment by coder-alpha** [comment]
@nedsolanki 
Disable SSL Web-Proxy
Set your base url to https://fmovies.taxi

Run Clear Cache and Reset Cookies under the Options menu and try again.

If you have a good internet connection (50Mbps or higher downloads) then you can raise the source searching and download thread values as well.

**Comment by Oldpapa** [comment]
I was close :)

**Comment by Kwakers01** [comment]
I have the same problem and I am also in the UK.  I am guessing the the UK ISPs have blocked access to the Base Site URLs rescently.  If I try to go to them via the web browser they are blocked.  I too have tried using the "Use SSL Web-Proxy" but I then get cookie errors even after resetting and clearing the cache.  I am running windows 10 (lastest update) and have tried 0.73 and 0.71 (which worked last time I used it a few months ago).  Is it possible to get passed the blocking using the "Use SSL Web-Proxy" as I really don't want to have to start looking at VPN's.  I am also guessing that trying to use the TOR browser would either not work or would be quite complicated to configure.

**Comment by coder-alpha** [comment]
@Kwakers01 
The `Use SSL Web-Proxy` was primarily to bypass the SSL issue on certain clients and as a secondary benefit access sites that might be blocked. However, now FMovies uses cookies as part of some checks in order to get to the video links and so the proxy method does not work for it.
There are other parts in the plugin like External Listing, External Sources, Searching which will use the proxy automatically as required.
To be honest I need to rethink or remove that option.

PS: TOR will not work since it's your PMS connection that needs to bypass not your browser.

**Comment by coder-alpha** [comment]
Closing for lack of further info. and probably blocked in UK. Solution would be to use External Listing and Search.
