### ISSUE TITLE
Token error is back

### ISSUE THREAD

**Issue by JameGumb** [coder-alpha/FMoviesPlus.bundle#42]
I was watching something and the channel worked great. Then went to watch another and got Video Unavailable. Error: token/PhantonJS disabled.  

Went into setting and enabled PhantomJS.  (which had been mysteriously disabled). Now just getting Video Unavailable. Error: token  and can't figure out how to fix it.   Did a cookie reset and still getting the error.

Thanks for all of your hard work CA, the channel is great and really appreciate it.

**Comment by ernstwildly** [comment]
I'm having the exact same issue as well.

**Comment by zablon123** [comment]
I wasn't seeing any issues last night other than for some reason you had to try 2-3 times before it would work.

**Comment by coder-alpha** [comment]
@zablon123 PhantomJS can have that issue where you might need to try 2-3 times before it is able to finish the process depending on your client time-out settings and your connection speed.

The fact it gives Token error even when PhantomJS is set to "Yes-Universally" probably means PhantomJS installation issue.

**Comment by coder-alpha** [comment]
A remote fix has been applied which should fix the issue and work without PhantomJS. Kindly confirm here after testing. Thanks.

**Comment by ernstwildly** [comment]
@coder-alpha Should I install the PhantomJS binary following the wiki instructions? I wasn't sure if that still needed to be done. The plug-in is working again for me since you did the remote fix.

**Comment by JameGumb** [comment]
Following directions and reset cookies, plug in is working great now. Thank you very much for fixing and for your hard work on this awesome plug in.  Much appreciated!

**Comment by coder-alpha** [comment]
@ernstwildly If you are ok with some of the down times caused when the token changes and also are not using OpenLoad links that frequently and/or do pairing for OpenLoad then you don't need PhantomJS.

@JameGumb Thanks for confirming !

**Comment by ernstwildly** [comment]
@coder-alpha So downloading the binary will help with down times (not that I've experienced many)?

**Comment by ernstwildly** [comment]
@coder-alpha I went ahead and installed PhantomJS anyways. Everything is working well now. Thank you again for resolving these issues.
