### ISSUE TITLE
Can't set download location

### ISSUE THREAD

**Issue by burner01** [coder-alpha/FMoviesPlus.bundle#44]
I've never been able to set the download location under download options; it always says "plugin not responding" whenever I click on download options. I don't have downloads disabled. What can I do to set the download location?

![2018-08-31 at 1 36 50 pm](https://user-images.githubusercontent.com/42874812/44927594-199d4d00-ad23-11e8-9cd4-4d845f924c95.png)

![2018-08-31 at 1 32 48 pm](https://user-images.githubusercontent.com/42874812/44927500-bb706a00-ad22-11e8-8ced-845700a9da00.png)

**Comment by burner01** [comment]
The library is defined (assuming the screenshot looks like it should), I even removed then re-added the folders, then restarted PMS, but I'm still getting "plugin is not responding". Is there a file where the download options are saved that can be edited to manually add the file path?  

![2018-08-31 at 4 32 48 pm](https://user-images.githubusercontent.com/42874812/44934807-3c882b00-ad3c-11e8-8725-3de43de6b330.png)

**Comment by coder-alpha** [comment]
The settings are stored in the Dict file of the plugin but will be difficult to edit/add directly. 

In the screencap you have posted there is an alert sign next to your Settings, that looks odd and might have something to do with access rights which could result in the plugin not able to access that information.

**Comment by burner01** [comment]
Yeah the server was unclaimed, once I claimed it, it worked. Thanks!
