### ISSUE TITLE
Unable to modify settings

### ISSUE THREAD

**Issue by privatadata** [coder-alpha/FMoviesPlus.bundle#45]
I tried to do a full reset of cache, cookies and everything else in Plex and this plugin.

Since then, if I go into setting for this plugin, I get the following error: 

Only the Admin can perform this action !

This is happening in Opera and Internet Explorer.

How do I fix this please?

**Comment by coder-alpha** [comment]
Assuming you are logged into Plex as the admin you might want to enable (or disable) the setting for Admin verification via Plex.tv or localhost to get it working.

![image](https://user-images.githubusercontent.com/10291660/45052551-2a1c3300-b055-11e8-9aeb-bf67892d6ff1.png)

**Comment by coder-alpha** [comment]
Closing for lack of further info.
