### ISSUE TITLE
New install, unable to use plugin due to cookie error

### ISSUE THREAD

**Issue by privatadata** [coder-alpha/FMoviesPlus.bundle#46]
I have just installed Plex for the first time and the most recent version of this plugin.

When I try to use it, I get the following error:

 
Cookie not set ! Please try Reset Cookies under the Options menu.

I reset cookies and cache within the plugin and this made no difference. I closed the Plex server and tab, reset my browser history, cookies and cache and re-ran and it still made no difference.

The error appears when I try to view 'Movies' or any other category. I have tried enabling PhantomJS, SSL, alternate SSL and many other combinations.

Please tell me how I can fix this.

**Comment by coder-alpha** [comment]
Please post a screencap of your Settings and your Device Options. 
It seems you have SSL Proxy enabled which should be left disabled. If you are on non-Windows OS you would probably need the Alternate SSL enabled. Do that and try resetting cookies again and see if that resolves the issue.

**Comment by privatadata** [comment]
Thanks for your reply. I am running Windows 10.

Problem with that is I then get the following error:

 
HTTP Code 0 for https://bmovies.online/home. Enable SSL option in Channel Prefs.

Same happens with other sources too like .taxi.

![image](https://user-images.githubusercontent.com/42977208/45056894-13450300-b08c-11e8-83ba-8d9a0025b5df.png)

![image](https://user-images.githubusercontent.com/42977208/45056928-2657d300-b08c-11e8-9ff0-e19fca7d417a.png)

Now sutr which screen you are referring to for Device Options.

**Comment by coder-alpha** [comment]
on Windows you dont need to enable the Alternate SSL option. 

Not sure why you're getting an error with bmovies.online when you have your Base set as fmovies.taxi.

Ensure under your Channel menu > Options > Tools > Set Base URL - you have fmovies.taxi set

Device Options are under Channel menu > Options > Device Options.

Also in your windows command prompt try to ping fmovies.taxi and make sure you are getting a byte response back.
![image](https://user-images.githubusercontent.com/10291660/45057410-9140e400-b063-11e8-9a90-36e4b2c504b8.png)

**Comment by privatadata** [comment]
I have tried both sources, what was shown in the screenshot was the second example.

![image](https://user-images.githubusercontent.com/42977208/45057902-e6461f80-b08e-11e8-8101-6adb10f6754a.png)


c:\Users>ping fmovies.taxi

Pinging fmovies.taxi [193.113.9.167] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 193.113.9.167:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

Does this have something to do with my ISP blocking these sources? I thought that the plugin automatically used proxies where required?

**Comment by Oldpapa** [comment]
Maybe your antivirus.

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 4, 2018 at 3:08 PM, privatadata<notifications@github.com> wrote:   
I have tried both sources, what was shown in the screenshot was the second example.



c:\Users>ping fmovies.taxi

Pinging fmovies.taxi [193.113.9.167] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 193.113.9.167:
Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

Does this have something to do with my ISP blocking these sources? I thought that the plugin automatically used proxies where required?

**Comment by privatadata** [comment]
None of my security software is blocking these requests according to the logfiles.

**Comment by coder-alpha** [comment]
@privatadata 
Somewhere there is a block, either ISP or somewhere else. The proxy does not apply for the fmovies listing since the retrieval of the links is not possible using that, their API needs cookie/referer info which is not possible when using a proxy.

You can use the External Listing or via Search and see what all is available using External Sources. To use the listing from fmovies you'll need to figure out where the blockage is.

**Comment by privatadata** [comment]
I know some sites are blocked by my ISP. If I attempt to access fmovies.se normally I get the following error:

This site can’t be reached
fmovies.se refused to connect.

Not sure whether that helps.

If I use the Opera built-in VPN I can access the site. Same if I use Hola. I was hoping that this plugin would remove the need for all that as I am having problems with RapidVideo lagging after 10 minutes every time I use it and wanted to rule out the VPN.

**Comment by Oldpapa** [comment]
Are you using malware bytes or hitman pro.. stuff like that?

**Comment by privatadata** [comment]
Not using Malwarebytes...

**Comment by coder-alpha** [comment]
Issue unrelated to plugin - https://github.com/coder-alpha/FMoviesPlus.bundle/issues/46#issuecomment-418518399
