### ISSUE TITLE
Error: Please give some time for the Interface to Load & Initialize plugins

### ISSUE THREAD

**Issue by wakiprats** [coder-alpha/FMoviesPlus.bundle#48]
Hi. Im new to this whole thing but i seem to be getting above error when trying to use Fmovies on plex. Any help would be appreciated

**Comment by sirthought** [comment]
Completely normal with this particular channel. It takes a few minutes for all of the connections to get in place. I often have to wait about four or five minutes if I've made a system update to FMovies Plus. Just sit tight for a bit and keep checking on it.

**Comment by wakiprats** [comment]
Thanks a lot. Working now. Another question, how do I search for certain movies / series?

**Comment by sirthought** [comment]
I usually first click on the Movies and TV-series icon and then I type a search for the program I'm looking for. If you are looking for a tv show that just recently aired, it's handy to first click on Whats Hot and then click on Latest TV-series. It'll list the last 16 programs to hit it's que. Sometime it can take a day or so for something to get a link in there. Not sure why but it's hard to complain, considering.

**Comment by sirthought** [comment]
If you are in the desktop browser, please click through to the icons suggested and then use the normal search bar provided in PLEX.

**Comment by coder-alpha** [comment]
@wakiprats which client are you using ?

If you are using a client which does not have a search feature then you can enable DumbKeyboard option located under Options > Device Options.

**Comment by wakiprats** [comment]
thanks a lot @sirthought and @coder-alpha. Working now.
