### ISSUE TITLE
Downloadin

### ISSUE THREAD

**Issue by drag0nb0x** [coder-alpha/FMoviesPlus.bundle#51]
So this isnt really a issue but i am late to the game here. Im sure it was coverd back at the old forums but for the life of me i can not figure out how to set the plugin to download anything. I notmally use it through the ruku,  i have my folders assigned but i cant find button so set the show to dl. Sorry to bother you oh masterfull one lol

**Comment by coder-alpha** [comment]
@drag0nb0x 
It is disabled under Settings by default. Once it is unchecked you should see menu items for downloading...

![image](https://user-images.githubusercontent.com/10291660/46702464-29953000-cbf1-11e8-9db1-59e03a68f47d.png)

![image](https://user-images.githubusercontent.com/10291660/46702600-bd66fc00-cbf1-11e8-8945-5662e1f59ea6.png)

![image](https://user-images.githubusercontent.com/10291660/46702848-b7254f80-cbf2-11e8-83df-da2d0147b80a.png)


Lol... masterfull one... that's a first.
