### ISSUE TITLE
can not get cookies to clear

### ISSUE THREAD

**Issue by JohnEngland65** [coder-alpha/FMoviesPlus.bundle#52]
in options I attempt to clear cookies and it runs its normal parameters.  I then go to movies and it says to clear cookies in potions? restarted and restarted pms also. Same thing clear cookies in options? TIA

**Comment by coder-alpha** [comment]
The site and all its redirectors are currently down. External Listing and Search with External is only working atm.

**Comment by coder-alpha** [comment]
The site seems back now so everything should be working as before.

**Comment by sirthought** [comment]
Thank you
