### ISSUE TITLE
Plugin Stuck In Initialization

### ISSUE THREAD

**Issue by MeanLauraJean** [coder-alpha/FMoviesPlus.bundle#54]
I am running the latest version of PMS and this plugin. So far after over 30 minutes initialization has not completed. In the past this only took 10 minutes so something seems amiss. Any thoughts?

**Comment by zablon123** [comment]
I have so many negative things to say about that...but what good would it do.

**Comment by coder-alpha** [comment]
@zablon123 
Yeah I know. Their status page https://status.plex.tv/ seems to suggest everything is back to normal even though Users have reported otherwise.
I'd suggest doing a Plex restart if the plugin has not initialized yet and you haven't done in the last few hours.

**Comment by zablon123** [comment]
Looks like it is still happening. Roku 3 / Win7 64bit. I'm on 1 version back from latest of PMS. What is odd is that Phantomjs never stops running, if you kill it, it just immediately starts back up. It is like that process is not completing/stuck in a loop. 

Only thing I know  changed is there was a Roku update and I rebooted it yesterday morning.

**Comment by coder-alpha** [comment]
@zablon123 
There are actually a number of mini PhantomJS processes that will run during initialization. If you feel that PhantomJS is the reason, you can disable PhantomJS under the settings and then restart Plex to have the plugin initialize without it and see if that works. 
![image](https://user-images.githubusercontent.com/10291660/48151405-2db77a80-e28f-11e8-9677-cf4b00167b30.png)

You can enable PhantomJS after the initialization has finished.

**Comment by zablon123** [comment]
That seems to have worked around the issue.  Start Plex --> Open Browser plugin --> disable PhantomJS --> wait for initialization to finish --> re-enable phantomjs

**Comment by coder-alpha** [comment]
> That seems to have worked around the issue. Start Plex --> Open Browser plugin --> disable PhantomJS --> wait for initialization to finish --> re-enable phantomjs

Thanks for confirming on that, I'll try to look into whats causing that issue later today.

**Comment by MeanLauraJean** [comment]
I don't this work around is cutting it anymore. Even with the phantomjs setting set to No at startup the initialization is taking a very long time.

**Comment by zablon123** [comment]
Yea, it does, but it does go, whereas otherwise it doesn't...at least that's my experience. As long as you get past it, it will stay fine until the next time plex is restarted (then you have to do it again).

**Comment by MeanLauraJean** [comment]
I'm at 40 minutes with it set to No. Pretty brutal.

**Comment by zablon123** [comment]
Yea, I dont know why it has that issue, but it does work, eventually with it on or off.

**Comment by coder-alpha** [comment]
40 mins is definitely too long. What I can suggest is to remove (physically delete the provider plugins) you are not using since it seems one or more of them are stuck. 

Also, those experiencing the issue, are you guys located outside the US and where some of the sites are blocked ? The plugin in such cases tries to use the proxy plugins one by one that could be adding to this long initialization process.

**Comment by coder-alpha** [comment]
I had a quick look and the YesMovies provider file could be the cause of long Initialization wait time due to the Cloudflare changing its check. I recommend moving the YesMovies provider file (yesmovies_mv_tv.py) to a different location outside the path of the FMovies plugin.

**Comment by MeanLauraJean** [comment]
Took your advice @coder-alpha on removing unused plugins and moving yesmovies_mv_tv.py (I put it in the disabled folder under sources) and it cut down the initialization to 5 minutes :) Thanks so much!

**Comment by coder-alpha** [comment]
With the v.0.74 update, instead of just the generic message "Please wait for plugin to load and initialize.." there is now a % progress indicator. Also the current Provider plugin file that is being initialized is shown, that is in case if the loading is stuck one can disable the faulty plugin file to fix Initialization issue.
