### ISSUE TITLE
plex updated and there is no channels for third party apps

### ISSUE THREAD

**Issue by JohnEngland65** [coder-alpha/FMoviesPlus.bundle#57]
Has anyone else had their plex app updated and unable to find channels to play third party apps

**Comment by coder-alpha** [comment]
Channels/Plugins has been removed from the Roku app. You can find more info on the forums about it.

**Comment by zablon123** [comment]
rarflix still works - just enter that as a private channel in your account. It is only the main channel that it is removed from - for now. The forums are pretty ugly at the moment.

**Comment by JohnEngland65** [comment]
How is fmovies loaded into rarflix?

**Comment by donmyfisher** [comment]
While the main Roku app no longer has channels on its updated Plex app, the older no longer updated  Plexrar app is still workable if you can find it to add to Roku. I used to use it, almost deleted it after they stopped updating it, but was glad to see all my channels in there when Roku updated the official app.

**Comment by zablon123** [comment]
Supposedly this works but I haven't tried it yet:

 In Roku, open the Roku Media Player (search for it, if you need to). Then select Video and keep diving down until you see the Plex channels. It’s definitely less convenient than using them inside the Plex app but nice that there’s a workaround (for now…)

**Comment by scottywh** [comment]
I was able to get rarflix to work here thankfully but man, what a pisser... Plex doing their best to make it hard to love these days.  Haven't managed to add "roku media player" yet so can't comment on that other than to say it wasn't super easy to find for me.

**Comment by zablon123** [comment]
If anyone is truly worried about losing everything, my suggestion is to block roku updates at your router. This will prevent the roku from removing rarflix (which is supposed to be happening in jan or february when the new API hits. I don't know what impact that will have after then, maybe it will all break and you'll be forced to let it update. Not sure, but it is a preventative measure.

**Comment by zablon123** [comment]
The roku media method does work, you just need to enable DLNA in your PMS. It's not as pretty, but it does allow the Fmovies plugin to work.

**Comment by zablon123** [comment]
okay - so found their twit, ffmovies.ru works.
