### ISSUE TITLE
Unable To Remove Bookmarks

### ISSUE THREAD

**Issue by MeanLauraJean** [coder-alpha/FMoviesPlus.bundle#58]
Happy New Year all! I am unable to remove individual bookmarks. The Add link is not replaced by the Remove link once a bookmark has been added. However the Clear all bookmarks functionality works. Is this a bug for anyone else?

**Comment by sirthought** [comment]
Yes that happens to me on some programs, but not all.

**Comment by coder-alpha** [comment]
Can you please test this if issue still persist with the latest v.0.74. Thnx

**Comment by MeanLauraJean** [comment]
Hey there! Unfortunately I'm still unable to remove individual bookmarks.

**Comment by coder-alpha** [comment]
> Hey there! Unfortunately I'm still unable to remove individual bookmarks.

Is this an old bookmark that you might have made or is the issue even with new ones ? If its only the old one, can you export your bookmarks and copy paste the relevant section of that old one. You can open the exported bookmarks file in any text editor.

**Comment by sirthought** [comment]
Where does one find the bookmarks to export? 

Thanks

**Comment by coder-alpha** [comment]
@sirthought 
FMovies menu > Options > Tools > Export Bookmarks

**Comment by MeanLauraJean** [comment]
The issue is with a new bookmark I just added. However I do have old bookmarks from pre v0.74 saved.

**Comment by coder-alpha** [comment]
I just tried with a new item 'Venom' and don't encounter any issue in adding/removing the Bookmark. What's the base url you are using under the Channel Prefs. ?

**Comment by MeanLauraJean** [comment]
It's working! I hadn't restarted PMS. After doing that the issue is resolved! Great work, thanks so much :)

PS: Is fmovies.taxi the best base URL to use? This thread can be closed after.

**Comment by coder-alpha** [comment]
Whichever works and is the fastest. I believe some might be blocked in some countries. Here in US, fmovies.taxi has worked well so far.
