### ISSUE TITLE
Unable to Play any Video

### ISSUE THREAD

**Issue by faizygr8** [coder-alpha/FMoviesPlus.bundle#59]
Hi I am Getting the Following Error When i Click on
Openload
Rapidvideo
Streamango 

Video Unavailable. Error: {u'message': u'preg_match(): Delimiter must not be alphanumeric or backslash', u'code': u'0', u'type': u'ErrorException'}

Tried with PhantomJS ON/OFF
and Have USS Also Installed
Tried with master and DEV Build also of USS
Tested on Windows FireFox Browser 
and FireTV Plex APP Also

Thanks

**Comment by coder-alpha** [comment]
Typically due to installation issues. Recommend using 7zip for unzipping the downloaded zip. Please attached zip of log files with debug enabled from the Channel Prefs. if issue persists.
