### ISSUE TITLE
Think I know the issue.

### ISSUE THREAD

**Issue by Shadyelements17** [coder-alpha/FMoviesPlus.bundle#6]
I discovered today that fmovies.to is not working but if you go to fmovies.io the link works. So I'm assuming this is why my plex isn't working. I tried to change it to that link in my setting but all I get is the dropdown menu of the previous 3 website links that don't work. Idk if this is the full solution but I'm pretty sure it's a big part of it.

**Comment by Heisenbear** [comment]
I hope this is still active and gets fixed!

**Comment by Shadyelements17** [comment]
I hope it gets fixed too! If not there's plenty of other great sites he could make an app for like hdonline.to and gomovies.to but with any site there's always the chance of them changing domains anytime for any reason.

**Comment by rdudeja1133** [comment]
You can add https://www.popcorn-time.to/ I always use this site for English/Hindi movies

Regards
RD

Sent from my iPhone

On Apr 25, 2017, at 8:20 PM, Shadyelements17 <notifications@github.com<mailto:notifications@github.com>> wrote:


I hope it gets fixed too! If not there's plenty of other great sites he could make an app for like hdonline.to and gomovies.to but with any site there's always the chance of them changing domains anytime for any reason.

**Comment by coder-alpha** [comment]
@Shadyelements17 @Heisenbear @rdudeja1133 
Working on a fix. fmovies.io is a different site (I might add it as an External Provider). The fmovies domains are .se, .is, .to. Travelling so getting limited time atm.

**Comment by coder-alpha** [comment]
@Shadyelements17 @Heisenbear @rdudeja1133
Can you guys try the latest version of the /master 0.17 and let me know. Do make sure u can visit fmovies.se before trying and if not wait to be unblocked before using... More posted here http://forums.plex.tv/discussion/comment/1427980/#Comment_1427980

**Comment by Heisenbear** [comment]
I will be trying this later tonight, I was still getting an error when trying to load the google links yesterday. Hopefully it will work though! I'll double check my settings when I get home from work.

**Comment by coder-alpha** [comment]
Partially down again... ---> http://forums.plex.tv/discussion/comment/1428329/#Comment_1428329
Try out the Extended Search in the mean time.

**Comment by Heisenbear** [comment]
I am currently getting "There are no playable items." now when I attempt to open any of the google/open/external links. I'm sorry for being such a hassle, but this bundle is like... my life blood, haha. I really appreciate all the hard work that goes into keeping this functioning. Any quick fix for this issue?

**Comment by Heisenbear** [comment]
Now "no videos based on filter selection". >.<

**Comment by rdudeja1133** [comment]
I am also seeing same issue

**Comment by coder-alpha** [comment]
@Heisenbear @rdudeja1133

Partially down... ---> http://forums.plex.tv/discussion/comment/1429559/#Comment_1429559
Use the Extended Search in the mean time.

**Comment by coder-alpha** [comment]
Fixed. Please read the forum thread for more info.
