### ISSUE TITLE
External sources hanging

### ISSUE THREAD

**Issue by grdon999** [coder-alpha/FMoviesPlus.bundle#61]
@coder-alpha I thought i would open this to continue our discussion. What i am seeing I think is external sources hanging, and that is then stopping Autopilot. Im not sure if it is always the same sources, and why it does not just timeout.  looking at Star Trek Discovery Season 2 episode 3 you can see from this screenshot that the external sources just keep spinning on 2 of them (IMDB, and FliXanity)

![image](https://user-images.githubusercontent.com/38835492/53244061-a1945c00-36a1-11e9-9a88-901c79302f5e.png)

**Comment by sirthought** [comment]
I'm getting the same hang on external sources. It's not just with autopilot. 

I did the steps you had recommended to look for the programs with *. I find the season and episode, but I can never get the sources to load for either streaming or download.

**Comment by JamminR** [comment]
Me also. Always hangs at 90% trying the alternate "*title" method. Version
.74

**Comment by grdon999** [comment]
So I tried a reinstall of fmovies by removing the bundle and redownloading, this time it hangs on different sources.

![image](https://user-images.githubusercontent.com/38835492/53246727-626a0900-36a9-11e9-9e37-f55fd7a5a7cc.png)

So Im not sure its an issue with the source. It almost looks like they are not returning a result back. The log seems to back up that assumption as you can see in the image above its still waiting on 3dfilms, but the log for 3dfilms shows 

![image](https://user-images.githubusercontent.com/38835492/53246834-a8bf6800-36a9-11e9-9878-06b0077b14c0.png)

So clearly it thinks it has finished and returned the result.

From what I can see so far it only does this when the providor does not have a matching result.

**Comment by grdon999** [comment]
OK, so it definalty seems to be that when the provider gets Could not find matching title rather than showing as complete in external sources it just sits there. Over to you @coder-alpha

**Comment by coder-alpha** [comment]
@grdon999 @sirthought @JamminR 
Thanks for all the info guys. I'll try and look into this by the weekend.

**Comment by grdon999** [comment]
@coder-alpha  let me know if you want me to do any debug type stuff.

**Comment by coder-alpha** [comment]
@grdon999 @sirthought @JamminR

Hi guys, can you test with the latest v.0.75 this issue of sources getting stuck in between.

I recommend a clean install. Stopping PMS. Deleting previous FMP version and then manually installing just to be sure all files get updated and also the moved Providers don't interfere.

I have also added a bit more logging and each plugin should have a "Complete" msg. logged once its process ends.
![image](https://user-images.githubusercontent.com/10291660/53295693-dfdb6980-37ce-11e9-9576-856f539a2675.png)

The latest ver. only has the following active Providers
![image](https://user-images.githubusercontent.com/10291660/53295701-2204ab00-37cf-11e9-96a3-3503f12e36d4.png)

**Comment by JamminR** [comment]
Good to know - WIll be a few hours/day or so before I can actually test. 
(It's extremely late where I am right now...starting to run on fumes)

I wouldn't have said anything at all yet, but... noticed from your images, seems to be searching for season and episode in S#E# format. Don't some/many releases have double digits, and, would that affect search?
(Example, S##E##) - I know most I rip/names I use double digit so they sort nice if they ever go into double digit seasons or eps (so that S1E1 isn't listed after S10E1 in an alphabetical sort)

**Comment by coder-alpha** [comment]
> Good to know - WIll be a few hours/day or so before I can actually test.
> (It's extremely late where I am right now...starting to run on fumes)

@JamminR 
I'll only get time again in the coming week now, so take your time guys.

> I wouldn't have said anything at all yet, but... noticed from your images, seems to be searching for season and episode in S#E# format. Don't some/many releases have double digits, and, would that affect search?
> (Example, S##E##) - I know most I rip/names I use double digit so they sort nice if they ever go into double digit seasons or eps (so that S1E1 isn't listed after S10E1 in an alphabetical sort)

Well the search happens very differently for each provider and none of them are as simple as comparing S#E#. In case where the match does have to be finally made, its easier to convert them into integers rather than as strings and then compare since you never know how many digits are used to represent season/episode. 
I think for downloading I'm using S#E##, so that can be made to do S##E## instead.

**Comment by JamminR** [comment]
@coder-alpha - Coming week? You must be at our immediate beck and call for when we find bugs, or make unruly requests!
In testing, I decided to have a look at a majority of my option settings. 

A) My maximum size setting for >=1-2 GB was disabled.
I don't remember ever doing that. Is there an odd bit of code setting that?

B) Proxy, only one listed, seems it can't be disabled.
I've never required one to my knowledge. Is that forced? Or is that a bug?

So far, everything else seems in working order, at least as far as I've delved.
I was able to see more listings for a bookmarked show than before, and able to start a download of a latest episode of one.

**Comment by JamminR** [comment]
Further testing of .75, external search didn't totally hang for me this time, but over 1.5 minutes to get full list, two big slow ones, at least according to details, were (Fmovies) and (GoWatchSeries). Both showed about 1 minute each. (I bumped my concurrent threads in main channel prefs from 3 to 4).

**Comment by coder-alpha** [comment]
@JamminR 
> @coder-alpha - Coming week? You must be at our immediate beck and call for when we find bugs, or make unruly requests!
> In testing, I decided to have a look at a majority of my option settings.
> 
> A) My maximum size setting for >=1-2 GB was disabled.
> I don't remember ever doing that. Is there an odd bit of code setting that?

The only option disabled in the Sizes list is the 0GB one by default, all other are enabled by default and that's the only place to set them.

> B) Proxy, only one listed, seems it can't be disabled.
> I've never required one to my knowledge. Is that forced? Or is that a bug?

Proxy don't have a disable option. If a site is not reachable via regular connection then only a connection via proxy is made for verification and used subsequently. If you want to disable it you will need to remove that proxy plugin and move it to its disabled folder.

> So far, everything else seems in working order, at least as far as I've delved.
> I was able to see more listings for a bookmarked show than before, and able to start a download of a latest episode of one.

Yeah enabling the plugin to show MyCloud listing (even though it's not playable) should have solved the issue of the missing episodes.

> Further testing of .75, external search didn't totally hang for me this time, but over 1.5 minutes to get full list, two big slow ones, at least according to details, were (Fmovies) and (GoWatchSeries). Both showed about 1 minute each. (I bumped my concurrent threads in main channel prefs from 3 to 4).

Yeah the match for show/episode typically takes a little longer than movies. Also depends if the initial search returned a lot of results and it tries to find the show first then find the matching season/episode. Bumping to more sources can work either way, so you'll have to find what works best.

**Comment by grdon999** [comment]
@coder-alpha Just tested the new version. I am still seeing external sources not complete. Whats interesting is the log shows they did complete.

![image](https://user-images.githubusercontent.com/38835492/53416839-3661c700-39cc-11e9-8da8-80885c731a67.png)

![image](https://user-images.githubusercontent.com/38835492/53416890-53969580-39cc-11e9-82b5-89766baa1f82.png)

**Comment by sirthought** [comment]
Since the latest update: I'm seeing the formerly missing episodes appear! Great news. I see folders for MyCloud (I know it won't work with Plex), Openload, Streamango, but Rapid no longer seems to be showing. Not a huge loss but that was usually the most reliable, as sometime Openload had issues due to captcha, and Streamango sometimes would give you files with no audio. I, too, am seeing the external sources hang, but it's less of a problem if those main sources work. Thanks for the continued support of this! 

<img width="1600" alt="screen shot 2019-02-26 at 8 56 19 am" src="https://user-images.githubusercontent.com/41130180/53417916-95abe100-39a4-11e9-846a-e515a06107f2.png">

**Comment by coder-alpha** [comment]
@sirthought 
Are those sources actually hanging or eventually do finish up ?
Typically each provider makes 5-6 http requests to finally find a match and then depending on the number of files hosts it find the time will increase. But it shouldn't take more than 5 min. for any. Primewire typically take long because of a number of host sources. Try a Refresh after the suggested ETA and then should all show completed with a min. or two of that.

**Comment by grdon999** [comment]
@coder-alpha The sources are still not completing. See the screen shot below, one of the sources is on 26122 seconds !

![image](https://user-images.githubusercontent.com/38835492/53445294-24057e80-3a08-11e9-96f9-a9573daca994.png)

**Comment by sirthought** [comment]
> @sirthought
> Are those sources actually hanging or eventually do finish up ?
> Typically each provider makes 5-6 http requests to finally find a match and then depending on the number of files hosts it find the time will increase. But it shouldn't take more than 5 min. for any. Primewire typically take long because of a number of host sources. Try a Refresh after the suggested ETA and then should all show completed with a min. or two of that.

Just did a couple tests. When I go through a bookmarked program now, I had to click multiple times and waited about 1 minute between and some options appeared on about the fourth click. When I searched for a program and choose the * option to drill through seasons and episodes, then it never completed it. I'd wait for 1 minute between each refresh, and finally tried waiting 10 minutes between a refresh. Still no options delivered. 

So, there is more progress than I was seeing before. Thank you for that!

**Comment by coder-alpha** [comment]
@grdon999 @sirthought 
Did this ever happen with 0.73 or previous versions ? Nothing has changed on the lib. front so I'm quite confused with this issue.
I'll try and test this with my other test VM PMS installations to see if I can replicate this.

**Comment by zablon123** [comment]
It's interesting that people  are seeing changes. I haven't updated mine and the missing stuff has reappeared as well as of a few days ago. I assume it was due to some changes on fmovies.

**Comment by sirthought** [comment]
> @grdon999 @sirthought
> Did this ever happen with 0.73 or previous versions ? Nothing has changed on the lib. front so I'm quite confused with this issue.
> I'll try and test this with my other test VM PMS installations to see if I can replicate this.

It always happened for me if I went to external sources. You had tried to guide me through suggestions before and they never worked. I just didn't want to keep bothering you with it. It's not that big of a problem if things like Streamango are working.

**Comment by grdon999** [comment]
@coder-alpha im ont sure. I could install .73 and test if you want

**Comment by grdon999** [comment]
@coder-alpha also i have not updated PMS for a while. im on 1.13.5.5291

**Comment by coder-alpha** [comment]
@grdon999 

Can you test this with IPv6 disabled on your system. I have read this before and recently again that it might cause some issues.

If that doesn't give any hints then a test with 0.73 would definitely confirm if this was recently introduced.

**Comment by grdon999** [comment]
I disabled ip6 and no change. I'll try rolling back the client when I get a chance

**Comment by coder-alpha** [comment]
@grdon999 
I guess that would help in narrowing it down. In the mean time I've added more logging in v.0.76. 

Things that might be helpful is the Control Log (under the Interface Options) that lists events that are going on in other parts of the code not covered by (Provider/Hosts/Proxy) logs.

Also added a Thread Status menu under options. The AutoPilot Queue and other threads that run will register here when active. There should be only 1 persisting thread when the plugin is idle.

As a last measure for the AutoPilot run the source searching is also limited by a [timeout](https://github.com/coder-alpha/FMoviesPlus.bundle/blob/master/Contents/Code/downloadsmenu.py#L13) that's set for 5 min. and should return in that time with whatever results get found.

**Comment by coder-alpha** [comment]
@grdon999 
I am able to replicate this on my NAS (WD PR4100). Works fine on Win10 & Ubuntu but I think its not an OS related issue. It also doesn't seem the thread is actually stuck but the status I'm setting to check has some issues. It might have been introduced when I added this check on the progress of initialization.

I have a feeling I know when the issue might be, just diagnosing on the NAS is a lil tricky.

**Comment by grdon999** [comment]
So looking at the new thread status menu I can see the search thread stuck. For instance searching for the orville i can see 2 stuck threads that dont seem to return
![image](https://user-images.githubusercontent.com/38835492/54214842-dea08100-44de-11e9-86d4-0d382ff7b94b.png)
But as you can see it has finished the search and not found any results
![image](https://user-images.githubusercontent.com/38835492/54214957-0a236b80-44df-11e9-8a6b-8d064b8bd139.png)

I think this is only an issue when it does not find a result.

**Comment by grdon999** [comment]
ill test the autopilot timeout. I noticed that autopilot now asks for a start and end series number. Do you have to specify the end one?

**Comment by grdon999** [comment]
I can confirm the timeout has fixed the autopilot issue

**Comment by coder-alpha** [comment]
@grdon999 
Thanks for confirming, I _think_ I know where the issue might be.

> ill test the autopilot timeout. I noticed that autopilot now asks for a start and end series number. Do you have to specify the end one?

So the idea initially of the AutoPilot was to automate download of all episode of a Show that has aired all it's episodes. In that case it was easy to get the end episode index.

The idea has now evolved into the ability to set AutoPilot to an ongoing Show and have an episode that was aired a day back pop up in your library. The issue when setting up AutoPilot for an ongoing Show is getting the end episode index. Even the OMDB API also does't provide that correct info all the time. So by default the Episode Start/End index is what the FMovies site provides. The next version will try and use meta from OMDB as well.

The way I am setting up currently is I set my End index to 20 (which typically should cover for most Shows). Currently there is not edit/update for the AutoPilot as well and the only way to Add to AutoPilot again is by deleting the existing Show Season entry from AutoPilot Queue & Downloads. The next version will address some of this.

> I can confirm the timeout has fixed the autopilot issue

Thanks, that's good to know.

**Comment by grdon999** [comment]
@coder-alpha So the timeout is definatly helping. When I set up an autopilot now after 5 minuts stuff starts to download. The only downside is when I look at thread status I see more and more unfinished threads. Do you want me to test or debug anything?

**Comment by coder-alpha** [comment]
@grdon999 
I think I know what the issue is. It's not the thread that's stuck per se but the thread status which I set that's at fault. 
I'll probably be putting out a `/dev` version later tonight. If you can test that out for the next few days, that would be great.

**Comment by grdon999** [comment]
@coder-alpha I have tried the new dev version (clean install) and still have the stuck threads issue.

**Comment by coder-alpha** [comment]
@grdon999 
Thanks, I've updated the `/dev` and tested on 2-3 platforms. I think this should now be fixed. Kindly test and confirm. Thanks.
PS: The Interface threads are now queried for their 'actual' alive status as well and should drop off within 2 sec. once they complete.

**Comment by grdon999** [comment]
@coder-alpha the dev version looks to be working. I have done a couple of searches and they now all complete fairly quickly. I have checked the providor log and can see searches returning no results, but this time the search finishes were as last time no result ment the thread looked to be hung. So so far so good.

**Comment by coder-alpha** [comment]
@grdon999 
Thanks for confirming. The thread was actually completing even before I was setting its state when `url == None`. :zipper_mouth_face:
