### ISSUE TITLE
Tools menu doesn't work 

### ISSUE THREAD

**Issue by moneycarlo** [coder-alpha/FMoviesPlus.bundle#62]
I upgraded my version to the .76 and now when I go into the tools menu on either the Plex app on my Samsung S7 phone or Samsung Smart TV I get an error. The air on my phone says the directory is empty. The air on the TV I can't recall exactly but it failed something with getitem.

**Comment by coder-alpha** [comment]
Did you perform a PMS restart ? Otherwise, the log file might be needed.

**Comment by moneycarlo** [comment]
Yup.  Logged into PMS and tried it from there and as soon as i click it, it said This plugin is not responding.

**Comment by coder-alpha** [comment]
When reporting issues please include the channel log file "com.plexapp.plugins.fmoviesplus.log"
[including numbered ones .1 through .5]
Reference Plex Log KB instructions - (https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files) or use WebTools > Logviewer/Downloader.
Please make sure to 'Enable Debug' option under the Setting/Prefs and replicate your issues before providing logs.

**Comment by moneycarlo** [comment]
So i just reinstalled via webtools this time (instead of inside the plugin), restarted pws and now it seems to work.

**Comment by coder-alpha** [comment]
FMP is quite complex and some times depending on the updated code, OS and other factors a proper update is not accomplished via the Internal Updater. Will look into this for future updates. Maybe add a flag to disable update via Internal Updater if that is the case.
