### ISSUE TITLE
Downloaded file at 100% stays stuck

### ISSUE THREAD

**Issue by coder-alpha** [coder-alpha/FMoviesPlus.bundle#63]
@grdon999

> Has anyone seen downloads finish, but not finish? So I downloaded the flash, season 5 episode 15 and it got to 100% but the entry is still in the downloading state. It has definatly finished as it is in my library and I can watch it. Ill try a restart at somepoint to see if that clears it.
> 
> So the download sitting at 100% has happened a few times. I think it is when the download source shows as direct. The download has finished and I can watch the episode.

@Kwakers01 

> I have restarted plex and cleared out failed downloads and deleted the directory that the file was in.
> Restarted the download and it has downloaded but is stuck at 100% again this is showing in the downloading page:-
> Better Call Saul S4E09 (2018) |Show| 0.268 GB - 480p | direct[GoWatchSeries] | Downloading - Started | ...
> and if I click on it this:-
> 100% | almost done | 0.16 MB/s ~ 0.36 MB/s ~ 0.35 MB/s | 0.268 GB - 480p | Started
> I will leave it like this for a while as I do not need to use the program at the moment. Let me know if you want me to click on anything.
> I have had not any problems with any films, could be a series issue or maybe a GoWatchSeries issue.

So I did have some weird issues going on with a direct source via GoWatchSeries. It was a vidcloud link which in the `/dev` version has been moved to its own host in case it requires disabling.. Not entirely sure why/whats the cause. I have a hunch for some reason the file closing operation of some files from this host gets stuck which leads to the issue.

Lets keep related discussion in this thread. I'll let you all know once I've got a new `/dev` version to test out this bug.

**Comment by coder-alpha** [comment]
@grdon999 @Kwakers01
Can you plz. confirm if this is still an issue. Moved the host (vidcloud) to it's own host from direct which should have fixed this issue.

**Comment by JamminR** [comment]
I had it happen to me today, but I was on /dev 3-18-2019 until about 3
hours ago.
Trying several shows/autopilot's now. Will let you know.

**Comment by coder-alpha** [comment]
@JamminR what was their host ? Did it say direct or vidcloud or something else ?

**Comment by JamminR** [comment]
I'm sorry - I didn't take note. I think they were GoStream, but I don't
remember what was in front of that.
I'll make absolutely sure to take note if they happen

**Comment by coder-alpha** [comment]
@JamminR 
Yes, the provider is definitely GoWatchSeries, whenever it happens again just note the host. I believe it should be either `direct` or `vidcloud`.

**Comment by grdon999** [comment]
@coder-alpha so far so good. Ill keep an eye on it

**Comment by coder-alpha** [comment]
This was due to an error for certain files when downloading the subtitle. This should be fixed by now with v 0.81 and above.
