### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by gary7653** [coder-alpha/FMoviesPlus.bundle#65]
Can not save bookmarks and old bookmarks do not work

**Comment by coder-alpha** [comment]
What the error when saving ?

**Comment by gary7653** [comment]
does not give the option to save

    On Monday, April 8, 2019, 5:41:57 PM EDT, Coder-Alpha <notifications@github.com> wrote:  
 
 
What the error when saving ?

**Comment by coder-alpha** [comment]
> does not give the option to save On Monday, April 8, 2019, 5:41:57 PM EDT, Coder-Alpha <notifications@github.com> wrote: What the error when saving ? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

@gary7653 
You should see the option to save and load. Make sure you're using a recent version of the plugin.

![image](https://user-images.githubusercontent.com/10291660/55768560-5795e880-5a4b-11e9-9d43-f581217e1fbd.png)

**Comment by gary7653** [comment]
please on your end search for the old show justified and then try and save it after you have found it. let me know how that goes for you. thanks

    On Monday, April 8, 2019, 10:12:34 PM EDT, Coder-Alpha <notifications@github.com> wrote:  
 
 

does not give the option to save On Monday, April 8, 2019, 5:41:57 PM EDT, Coder-Alpha notifications@github.com wrote: What the error when saving ? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.


@gary7653
You should see the option to save and load. Make sure you're using a recent version of the plugin.

**Comment by gary7653** [comment]
using yesterday's version

**Comment by gary7653** [comment]
i have the latest version as of 4/9/19. i have been using f-movie plus for about 2 years with very few problems and i thank you for that. when i try to use my saved bookmarks that i have been using it says no other seasons available currently. when i search some of my shows like justified it does not give me a way to save it to bookmarks. please tell me what i am doing wrong. thanks

    On Tuesday, April 9, 2019, 5:43:06 AM EDT, Gary M Stainback <garymstainback@yahoo.com> wrote:  
 
  please on your end search for the old show justified and then try and save it after you have found it. let me know how that goes for you. thanks

    On Monday, April 8, 2019, 10:12:34 PM EDT, Coder-Alpha <notifications@github.com> wrote:  
 
 

does not give the option to save On Monday, April 8, 2019, 5:41:57 PM EDT, Coder-Alpha notifications@github.com wrote: What the error when saving ? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.


@gary7653
You should see the option to save and load. Make sure you're using a recent version of the plugin.

**Comment by coder-alpha** [comment]
@gary7653 

The FMovies site has implemented a captcha system. Regular functioning will currently not be available. External Listing and Sources are available. Please read more on the [Discussion thread](https://github.com/coder-alpha/FMoviesPlus.bundle/issues/33#issuecomment-481045286).

**Comment by coder-alpha** [comment]
@gary7653 
Bookmarking of External Search items (items marked with leading *) is now available in v.0.82

**Comment by gary7653** [comment]
thank you very much

    On Friday, April 12, 2019, 4:04:53 PM EDT, Coder-Alpha <notifications@github.com> wrote:  
 
 
@gary7653
Bookmarking of External Search items (items marked with leading *) is now available in v.0.82
