### ISSUE TITLE
Can we get an option to use our own Fmovies url in the settings?

### ISSUE THREAD

**Issue by bodgeuppm** [coder-alpha/FMoviesPlus.bundle#67]
Can we get an option to enter custom urls in the settings rather than editing the DefaultPrefs.json file??  Just the last link i was able to use bmovies.club went down recently and either my ISP has blocked the others or there completely down so i ended up adding ffmovies.to to the Defaultprefs.json file to get my plugin working again.  But id love it if we could type a url in the settings rather than keep editing the json file?

**Comment by coder-alpha** [comment]
Implemented in [v 0.83](https://github.com/coder-alpha/FMoviesPlus.bundle/releases/tag/v0.83)

**Comment by bodgeuppm** [comment]
many thanks, just got to work out why i can get a url to work via a browser but the plugin returns 0 movies, but thats for another thread?

**Comment by JamminR** [comment]
Depends. Is it a url that is part of the true Fmovies (or other site fmp
already understands) system?
Fmp won't be able to read just any content site.

**Comment by coder-alpha** [comment]
@bodgeuppm 
As @JamminR says and those are updated on their twitter https://twitter.com/fmoviesdotto
